### PR TITLE
Fix outdated code in reports endpoints

### PR DESCRIPTION
**Pull request by mtourj**
# Description

Fix two breaking, but small issues  in reports endpoints

### CODE REVIEW

**Comment by katie-rose** [comment]
@sumeet-bansal how do we get this to pass CI?

**Comment by sumeet-bansal** [comment]
> @sumeet-bansal how do we get this to pass CI?

@katie-rose You can click ["Details"](https://app.circleci.com/pipelines/github/Lambda-School-Labs/key-conservation-be/240/workflows/f1555bbd-2ff0-4862-8a4f-04c9d3cd081d/jobs/242/steps) on the failing CI job and see the error. In this case, it's because there's a `console.log` in the `reports` controller. You can delete the `console.log` if it's just being used for debugging or if it's logging something important, import the logger from `./app/logger` and use that.

**Comment by mtourj** [comment]
lint rolled - good to go

**Comment by sumeet-bansal** [comment]
Can you also delete the comment disabling the linter ([here](https://github.com/Lambda-School-Labs/key-conservation-be/pull/214/files#diff-8db261a00087d5d2a3dd2f1ee79f5214R1)) before you merge?

**Comment by mtourj** [comment]
Sure thing

**Comment by mtourj** [comment]
Lol no rush. Gracias!

**Comment by mtourj** [comment]
The green button is yours to click @katie-rose

**Pull request merged**
